services:
  - type: web
    name: tradingpnl-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: BIND_HOST
        value: 0.0.0.0
      - key: ARBITRUM_RPC
        value: https://sepolia-rollup.arbitrum.io/rpc
      - key: USDC_ADDRESS
        value: 0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d
      - key: TRADING_VAULT_ADDRESS
        value: 0x4Fa9293827922f4688d7365a9E92B3468c02CcC7
      - key: KEEPER_PRIVATE_KEY
        value: 4dc584c9de1895ed644fb7548dba24cb35c7f5d5b0e87ba9b84d1c9427d5ed70
      - key: DATABASE_URL
        fromDatabase:
          name: tradingpnl-db
          property: connectionString

databases:
  - name: tradingpnl-db
    plan: free
    databaseName: tradingpnl
    user: postgres
