import { MarketConfig } from './BTC-PERP';

export const DOGE_PERP: MarketConfig = {
  ticker: 'DOGE-PERP',
  name: 'Dogecoin',
  category: 'crypto',
  baseAsset: 'DOGE',
  quoteAsset: 'USDC',
  pairId: 4,
  tvSymbol: 'BINANCE:DOGEUSDT',
  cbProduct: 'DOGE-USD',
  pythFeedId: '0xdcef50dd0a4cd2dcc17e45df1676dcb336a11a61c69df7a023097610cf4f840f',
  tickSize: 0.00001,
  stepSize: 10,
  minOrderSize: 10,
  maxOrderSize: 1000000.0,
  maxLeverage: 20,
  defaultLeverage: 10,
  initialMarginBps: 500,
  maintenanceMarginBps: 250,
  makerFeeBps: 2,
  takerFeeBps: 6,
  strikeRound: 0.01,
  baseIV: 0.88,
  expiryPresets: ['1h', '4h', '24h'],
  priceDecimals: 4,
  sizeDecimals: 1,
  badge: 'Meme Sector',
  description: 'Dogecoin Perpetual contract with high volatility and decentralized oracle feed.'
};
