import { MarketConfig } from './BTC-PERP';

export const SOL_PERP: MarketConfig = {
  ticker: 'SOL-PERP',
  name: 'Solana',
  category: 'crypto',
  baseAsset: 'SOL',
  quoteAsset: 'USDC',
  pairId: 3,
  tvSymbol: 'COINBASE:SOLUSD',
  cbProduct: 'SOL-USD',
  pythFeedId: '0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d',
  tickSize: 0.01,
  stepSize: 0.1,
  minOrderSize: 0.1,
  maxOrderSize: 5000.0,
  maxLeverage: 50,
  defaultLeverage: 15,
  initialMarginBps: 200,
  maintenanceMarginBps: 100,
  makerFeeBps: 2,
  takerFeeBps: 5.5,
  strikeRound: 5,
  baseIV: 0.76,
  expiryPresets: ['1h', '4h', '24h'],
  priceDecimals: 2,
  sizeDecimals: 2,
  badge: 'High Beta',
  description: 'Solana Perpetual contract featuring high-velocity order routing and continuous funding.'
};
