import { Market } from '../types';

export const MARKETS: Record<string, Market> = {
  'BTC-PERP': {
    name: 'Bitcoin',
    ticker: 'BTC-PERP',
    base: 'BTC',
    tvSymbol: 'COINBASE:BTCUSD',
    cbProduct: 'BTC-USD',
    strikeRound: 500,
    decimals: 2,
    category: 'crypto',
    maxLeverage: 100,
    icon: '/tokens/Bitcoin.svg.webp'
  },
  'ETH-PERP': {
    name: 'Ethereum',
    ticker: 'ETH-PERP',
    base: 'ETH',
    tvSymbol: 'COINBASE:ETHUSD',
    cbProduct: 'ETH-USD',
    strikeRound: 50,
    decimals: 2,
    category: 'crypto',
    maxLeverage: 100,
    icon: '/tokens/ETH.png'
  },
  'SOL-PERP': {
    name: 'Solana',
    ticker: 'SOL-PERP',
    base: 'SOL',
    tvSymbol: 'COINBASE:SOLUSD',
    cbProduct: 'SOL-USD',
    strikeRound: 5,
    decimals: 2,
    category: 'crypto',
    maxLeverage: 50,
    icon: '/tokens/Solana_logo.png'
  },
  'DOGE-PERP': {
    name: 'Dogecoin',
    ticker: 'DOGE-PERP',
    base: 'DOGE',
    tvSymbol: 'COINBASE:DOGEUSD',
    cbProduct: 'DOGE-USD',
    strikeRound: 0.01,
    decimals: 4,
    category: 'crypto',
    maxLeverage: 50,
    icon: '/tokens/Dogecoin_Logo.png'
  },
  'BNB-PERP': {
    name: 'BNB',
    ticker: 'BNB-PERP',
    base: 'BNB',
    tvSymbol: 'BINANCE:BNBUSDT',
    cbProduct: 'BNB-USD',
    strikeRound: 10,
    decimals: 2,
    category: 'crypto',
    maxLeverage: 50,
    icon: '/tokens/bnb.png'
  },
  'ZEC-PERP': {
    name: 'Zcash',
    ticker: 'ZEC-PERP',
    base: 'ZEC',
    tvSymbol: 'COINBASE:ZECUSD',
    cbProduct: 'ZEC-USD',
    strikeRound: 10,
    decimals: 2,
    category: 'crypto',
    maxLeverage: 25,
    icon: '/tokens/ZEC.png'
  },
  'LIT-PERP': {
    name: 'Litentry',
    ticker: 'LIT-PERP',
    base: 'LIT',
    tvSymbol: 'BINANCE:LITUSDT',
    cbProduct: 'LIT-USD',
    strikeRound: 0.01,
    decimals: 4,
    category: 'crypto',
    maxLeverage: 20,
    icon: '/tokens/LIT.png'
  },
  'ARB-PERP': {
    name: 'Arbitrum',
    ticker: 'ARB-PERP',
    base: 'ARB',
    tvSymbol: 'COINBASE:ARBUSD',
    cbProduct: 'ARB-USD',
    strikeRound: 0.05,
    decimals: 4,
    category: 'crypto',
    maxLeverage: 50,
    icon: '/tokens/ARB.png'
  },
  'NEAR-PERP': {
    name: 'NEAR Protocol',
    ticker: 'NEAR-PERP',
    base: 'NEAR',
    tvSymbol: 'COINBASE:NEARUSD',
    cbProduct: 'NEAR-USD',
    strikeRound: 0.1,
    decimals: 4,
    category: 'crypto',
    maxLeverage: 50,
    icon: '/tokens/NEAR.png'
  },
  'UNI-PERP': {
    name: 'Uniswap',
    ticker: 'UNI-PERP',
    base: 'UNI',
    tvSymbol: 'COINBASE:UNIUSD',
    cbProduct: 'UNI-USD',
    strikeRound: 0.2,
    decimals: 3,
    category: 'crypto',
    maxLeverage: 50,
    icon: '/tokens/UNI.png'
  },
  'GMX-PERP': {
    name: 'GMX',
    ticker: 'GMX-PERP',
    base: 'GMX',
    tvSymbol: 'BINANCE:GMXUSDT',
    cbProduct: 'GMX-USD',
    strikeRound: 0.5,
    decimals: 2,
    category: 'crypto',
    maxLeverage: 30,
    icon: '/tokens/GMX.png'
  },
  'XRP-PERP': {
    name: 'XRP',
    ticker: 'XRP-PERP',
    base: 'XRP',
    tvSymbol: 'COINBASE:XRPUSD',
    cbProduct: 'XRP-USD',
    strikeRound: 0.05,
    decimals: 4,
    category: 'crypto',
    maxLeverage: 50,
    icon: '/tokens/XRP.png'
  },
  'NVDA-PERP': {
    name: 'NVIDIA Corp',
    ticker: 'NVDA-PERP',
    base: 'NVDA',
    tvSymbol: 'NASDAQ:NVDA',
    cbProduct: 'NVDA',
    strikeRound: 2,
    decimals: 2,
    category: 'stocks',
    maxLeverage: 20,
    icon: '/tokens/NVDA.png'
  },
  'SPY-PERP': {
    name: 'S&P 500 ETF',
    ticker: 'SPY-PERP',
    base: 'SPY',
    tvSymbol: 'AMEX:SPY',
    cbProduct: 'SPY',
    strikeRound: 1,
    decimals: 2,
    category: 'stocks',
    maxLeverage: 20,
    icon: '/tokens/SPY.png'
  },
  'TSLA-PERP': {
    name: 'Tesla Inc',
    ticker: 'TSLA-PERP',
    base: 'TSLA',
    tvSymbol: 'NASDAQ:TSLA',
    cbProduct: 'TSLA',
    strikeRound: 5,
    decimals: 2,
    category: 'stocks',
    maxLeverage: 20,
    icon: '/tokens/TSLA.png'
  }
};
